### PR TITLE
My first Contribution!

### PR DESCRIPTION
**Pull request by cobrbra**
Including an image and a .dprec movie. Will work out how to change that to .mov at a later date.

### CODE REVIEW

**Comment by cobrbra** [comment]
Resolves issue #3

**Comment by stevenaeola** [comment]
That's real pretty Jacob!

**Comment by cobrbra** [comment]
Cheers!

Now I’m a contributor, if I was to faff around with something, wanted to show you what it looked like but didn’t want necessarily to incorporate it before you’d seen, what would be the best way to go about that?

**Comment by stevenaeola** [comment]
Make a feature branch:

https://www.atlassian.com/git/tutorials/using-branches

Then you can pull the branch into the main branch when we’re all happy.

If you’re really interested in git then this paper is worth reading

https://jwiegley.github.io/git-from-the-bottom-up/

Cheers,

   Steven

On 4 Dec 2018, at 22:53, cobrbra <notifications@github.com<mailto:notifications@github.com>> wrote:

Cheers!

Now I’m a contributor, if I was to faff around with something, wanted to show you what it looked like but didn’t want necessarily to incorporate it before you’d seen, what would be the best way to go about that?

**Pull request merged**
